version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: local_postgres
    restart: always
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: dev_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dev_network

  mongodb:
    image: mongo:7.0
    container_name: local_mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev_user
      MONGO_INITDB_ROOT_PASSWORD: dev_password
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - dev_network

  elasticsearch:
    image: elasticsearch:8.12.2
    container_name: local_elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false 
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - dev_network

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: local_rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: dev_user
      RABBITMQ_DEFAULT_PASS: dev_password
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - dev_network

  redis:
    image: redis:7.2-alpine
    container_name: local_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - dev_network

  minio:
    image: minio/minio:latest
    container_name: local_minio
    restart: always
    environment:
      MINIO_ROOT_USER: dev_user
      MINIO_ROOT_PASSWORD: dev_password
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - dev_network

  app:
    build: 
      context: .
      dockerfile: Dockerfile
  
    container_name: rag_app
    working_dir: /app
    ports:
      - "8585:8585"
    volumes:
      - .:/app
    command: tail -f /dev/null
    networks:
      - dev_network
    depends_on:
      - postgres
      - mongodb
      - redis
      - rabbitmq
      - elasticsearch
      - minio
    device_requests:
      - driver: nvidia
        count: all
        capabilities: [gpu]

volumes:
  postgres_data:
  mongodb_data:
  elasticsearch_data:
  rabbitmq_data:
  redis_data:
  minio_data:


networks:
  dev_network:
    driver: bridge